export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "CSS"
  | "AJAX"
  | "Laravel"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "Liquid"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "JavaScript"
  | "jQuery"
  | "Tailwind CSS"
  | "HTML"
  | "Amazon SES"
  | "NoSQL"
  | "Cron Jobs"
  | "C++"
  | "File I/O"
  | "REST APIs"
  | "C# (.NET)"
  | "RDBMS"
  | "SQL"
  | "Remix"
  | "NodeJS"
  | "Shopify"
  | "Node"
  | "NodeJs"
  | "File System"
  | "Console App"
  | "React(Remix)"
  | "WebSocket"
  | "Shopify API"
  | "Framer Motion";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "Workflow Automation"
  | "Live Streaming"
  | "Inventory"
  | "Inventory Management"
  | "Web Development"
  | "Integration"
  | "Desktop App"
  | "C++"
  | "File System"
  | "E-commerce"
  | "Automation"
  | "Rental System"
  | "3D Modeling";

export type ValidExpType = "Personal" | "Professional" | "Academic";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume";
