export const siteConfig = {
  name: "Ankit Sen | Full Stack Developer Portfolio",
  authorName: "Ankit Sen",
  username: "senankit379",
  description:
    "Ankit Sen's portfolio - Experienced Full Stack Developer based in Bhopal specializing in Node.js, Laravel, PHP, Remix, and Data Structures & Algorithms (DSA). Showcasing scalable web applications, e-commerce optimization, and problem-solving expertise.",
  url: "https://your-portfolio-url.com",  // Replace with your actual portfolio URL
  links: {
    twitter: "https://x.com/senankit379",
    github: "https://github.com/senankit379",
    linkedin: "https://www.linkedin.com/in/ankit-sen-29778320a",
    email: "mailto:senankit379@gmail.com",
  },
  ogImage: "https://your-portfolio-url.com/profile-img.jpg",
  iconIco: "https://your-portfolio-url.com/favicon.ico",
  logoIcon: "https://your-portfolio-url.com/logo.png",
  keywords: [
    "Ankit Sen",
    "Full Stack Developer Bhopal",
    "Software Developer Bhopal",
    "Laravel Developer Bhopal",
    "Node.js Developer Bhopal",
    "PHP Developer Bhopal",
    "Remix Developer Bhopal",
    "DSA Developer Bhopal",
    "Data Structures and Algorithms Bhopal",
    "Web Developer Bhopal",
    "E-commerce Developer Bhopal",
    "Frontend Developer Bhopal",
    "Backend Developer Bhopal",
    "React Developer Bhopal",
    "Next.js Developer Bhopal",
    "Tailwind CSS Developer Bhopal",
    "JavaScript Developer Bhopal",
    "Full Stack Engineer Bhopal",
    "Software Engineer Bhopal",
    "Bhopal Software Developer",
    "Bhopal Laravel Developer",
    "Bhopal Node.js Developer",
    "Bhopal PHP Developer",
    "Bhopal Remix Developer",
    "Bhopal DSA Expert",
    "Bhopal Coding Challenge Solver",
    "Bhopal Application Developer",
    "Bhopal Web Application Developer",
    "Modern Developer Bhopal",
    "Open Source Developer Bhopal",
    "Career Portfolio Bhopal",
    "Developer Portfolio Bhopal",
    "GitHub Developer Bhopal",
    "Responsive Web Developer Bhopal",
  ],
};
